
export const routeName = {
    login: "login",
    dashboard: "dashboard",
    users: "users",
    createUser: "create-user",
    roles: "roles",
    roleDetail: "roleDetail",
    companies: "companies",
    createCompany: "create-company",
    countries: "countries",
    createCountry: "create-country",
    privacyPolicy: "privacy-policy",
    me: "me",
    profile: "profile",
    photo: "photo",
    photoList: "photo-list",
    photoGallery: "photo-gallery",
    customer: "customer",
    merchandiserCustomer: "merchandiser-customer",
    salesCustomer: "sales-customer",
    others: "*",
};